/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTeamsTeamIdRouteRouteImport } from './routes/_authenticated/teams/$teamId/route'
import { Route as AuthenticatedTeamsTeamIdIndexRouteImport } from './routes/_authenticated/teams/$teamId/index'
import { Route as AuthenticatedTeamsTeamIdUsersRouteRouteImport } from './routes/_authenticated/teams/$teamId/users/route'
import { Route as AuthenticatedTeamsTeamIdServiceAccountsRouteRouteImport } from './routes/_authenticated/teams/$teamId/service-accounts/route'
import { Route as AuthenticatedTeamsTeamIdRolesRouteRouteImport } from './routes/_authenticated/teams/$teamId/roles/route'
import { Route as AuthenticatedTeamsTeamIdPoliciesRouteRouteImport } from './routes/_authenticated/teams/$teamId/policies/route'
import { Route as AuthenticatedTeamsTeamIdUsersIndexRouteImport } from './routes/_authenticated/teams/$teamId/users/index'
import { Route as AuthenticatedTeamsTeamIdServiceAccountsIndexRouteImport } from './routes/_authenticated/teams/$teamId/service-accounts/index'
import { Route as AuthenticatedTeamsTeamIdRolesIndexRouteImport } from './routes/_authenticated/teams/$teamId/roles/index'
import { Route as AuthenticatedTeamsTeamIdPoliciesIndexRouteImport } from './routes/_authenticated/teams/$teamId/policies/index'
import { Route as AuthenticatedTeamsTeamIdUsersUserIdRouteRouteImport } from './routes/_authenticated/teams/$teamId/users/$userId/route'
import { Route as AuthenticatedTeamsTeamIdUsersUserIdIndexRouteImport } from './routes/_authenticated/teams/$teamId/users/$userId/index'
import { Route as AuthenticatedTeamsTeamIdServiceAccountsServiceAccountIdIndexRouteImport } from './routes/_authenticated/teams/$teamId/service-accounts/$serviceAccountId/index'
import { Route as AuthenticatedTeamsTeamIdPoliciesPolicyIdIndexRouteImport } from './routes/_authenticated/teams/$teamId/policies/$policyId/index'
import { Route as AuthenticatedTeamsTeamIdUsersUserIdRolesIndexRouteImport } from './routes/_authenticated/teams/$teamId/users/$userId/roles/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeamsTeamIdRouteRoute =
  AuthenticatedTeamsTeamIdRouteRouteImport.update({
    id: '/teams/$teamId',
    path: '/teams/$teamId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeamsTeamIdIndexRoute =
  AuthenticatedTeamsTeamIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTeamsTeamIdRouteRoute,
  } as any)
const AuthenticatedTeamsTeamIdUsersRouteRoute =
  AuthenticatedTeamsTeamIdUsersRouteRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedTeamsTeamIdRouteRoute,
  } as any)
const AuthenticatedTeamsTeamIdServiceAccountsRouteRoute =
  AuthenticatedTeamsTeamIdServiceAccountsRouteRouteImport.update({
    id: '/service-accounts',
    path: '/service-accounts',
    getParentRoute: () => AuthenticatedTeamsTeamIdRouteRoute,
  } as any)
const AuthenticatedTeamsTeamIdRolesRouteRoute =
  AuthenticatedTeamsTeamIdRolesRouteRouteImport.update({
    id: '/roles',
    path: '/roles',
    getParentRoute: () => AuthenticatedTeamsTeamIdRouteRoute,
  } as any)
const AuthenticatedTeamsTeamIdPoliciesRouteRoute =
  AuthenticatedTeamsTeamIdPoliciesRouteRouteImport.update({
    id: '/policies',
    path: '/policies',
    getParentRoute: () => AuthenticatedTeamsTeamIdRouteRoute,
  } as any)
const AuthenticatedTeamsTeamIdUsersIndexRoute =
  AuthenticatedTeamsTeamIdUsersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTeamsTeamIdUsersRouteRoute,
  } as any)
const AuthenticatedTeamsTeamIdServiceAccountsIndexRoute =
  AuthenticatedTeamsTeamIdServiceAccountsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTeamsTeamIdServiceAccountsRouteRoute,
  } as any)
const AuthenticatedTeamsTeamIdRolesIndexRoute =
  AuthenticatedTeamsTeamIdRolesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTeamsTeamIdRolesRouteRoute,
  } as any)
const AuthenticatedTeamsTeamIdPoliciesIndexRoute =
  AuthenticatedTeamsTeamIdPoliciesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTeamsTeamIdPoliciesRouteRoute,
  } as any)
const AuthenticatedTeamsTeamIdUsersUserIdRouteRoute =
  AuthenticatedTeamsTeamIdUsersUserIdRouteRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => AuthenticatedTeamsTeamIdUsersRouteRoute,
  } as any)
const AuthenticatedTeamsTeamIdUsersUserIdIndexRoute =
  AuthenticatedTeamsTeamIdUsersUserIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTeamsTeamIdUsersUserIdRouteRoute,
  } as any)
const AuthenticatedTeamsTeamIdServiceAccountsServiceAccountIdIndexRoute =
  AuthenticatedTeamsTeamIdServiceAccountsServiceAccountIdIndexRouteImport.update(
    {
      id: '/$serviceAccountId/',
      path: '/$serviceAccountId/',
      getParentRoute: () => AuthenticatedTeamsTeamIdServiceAccountsRouteRoute,
    } as any,
  )
const AuthenticatedTeamsTeamIdPoliciesPolicyIdIndexRoute =
  AuthenticatedTeamsTeamIdPoliciesPolicyIdIndexRouteImport.update({
    id: '/$policyId/',
    path: '/$policyId/',
    getParentRoute: () => AuthenticatedTeamsTeamIdPoliciesRouteRoute,
  } as any)
const AuthenticatedTeamsTeamIdUsersUserIdRolesIndexRoute =
  AuthenticatedTeamsTeamIdUsersUserIdRolesIndexRouteImport.update({
    id: '/roles/',
    path: '/roles/',
    getParentRoute: () => AuthenticatedTeamsTeamIdUsersUserIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/teams/$teamId': typeof AuthenticatedTeamsTeamIdRouteRouteWithChildren
  '/teams/$teamId/policies': typeof AuthenticatedTeamsTeamIdPoliciesRouteRouteWithChildren
  '/teams/$teamId/roles': typeof AuthenticatedTeamsTeamIdRolesRouteRouteWithChildren
  '/teams/$teamId/service-accounts': typeof AuthenticatedTeamsTeamIdServiceAccountsRouteRouteWithChildren
  '/teams/$teamId/users': typeof AuthenticatedTeamsTeamIdUsersRouteRouteWithChildren
  '/teams/$teamId/': typeof AuthenticatedTeamsTeamIdIndexRoute
  '/teams/$teamId/users/$userId': typeof AuthenticatedTeamsTeamIdUsersUserIdRouteRouteWithChildren
  '/teams/$teamId/policies/': typeof AuthenticatedTeamsTeamIdPoliciesIndexRoute
  '/teams/$teamId/roles/': typeof AuthenticatedTeamsTeamIdRolesIndexRoute
  '/teams/$teamId/service-accounts/': typeof AuthenticatedTeamsTeamIdServiceAccountsIndexRoute
  '/teams/$teamId/users/': typeof AuthenticatedTeamsTeamIdUsersIndexRoute
  '/teams/$teamId/policies/$policyId': typeof AuthenticatedTeamsTeamIdPoliciesPolicyIdIndexRoute
  '/teams/$teamId/service-accounts/$serviceAccountId': typeof AuthenticatedTeamsTeamIdServiceAccountsServiceAccountIdIndexRoute
  '/teams/$teamId/users/$userId/': typeof AuthenticatedTeamsTeamIdUsersUserIdIndexRoute
  '/teams/$teamId/users/$userId/roles': typeof AuthenticatedTeamsTeamIdUsersUserIdRolesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/teams/$teamId': typeof AuthenticatedTeamsTeamIdIndexRoute
  '/teams/$teamId/policies': typeof AuthenticatedTeamsTeamIdPoliciesIndexRoute
  '/teams/$teamId/roles': typeof AuthenticatedTeamsTeamIdRolesIndexRoute
  '/teams/$teamId/service-accounts': typeof AuthenticatedTeamsTeamIdServiceAccountsIndexRoute
  '/teams/$teamId/users': typeof AuthenticatedTeamsTeamIdUsersIndexRoute
  '/teams/$teamId/policies/$policyId': typeof AuthenticatedTeamsTeamIdPoliciesPolicyIdIndexRoute
  '/teams/$teamId/service-accounts/$serviceAccountId': typeof AuthenticatedTeamsTeamIdServiceAccountsServiceAccountIdIndexRoute
  '/teams/$teamId/users/$userId': typeof AuthenticatedTeamsTeamIdUsersUserIdIndexRoute
  '/teams/$teamId/users/$userId/roles': typeof AuthenticatedTeamsTeamIdUsersUserIdRolesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/teams/$teamId': typeof AuthenticatedTeamsTeamIdRouteRouteWithChildren
  '/_authenticated/teams/$teamId/policies': typeof AuthenticatedTeamsTeamIdPoliciesRouteRouteWithChildren
  '/_authenticated/teams/$teamId/roles': typeof AuthenticatedTeamsTeamIdRolesRouteRouteWithChildren
  '/_authenticated/teams/$teamId/service-accounts': typeof AuthenticatedTeamsTeamIdServiceAccountsRouteRouteWithChildren
  '/_authenticated/teams/$teamId/users': typeof AuthenticatedTeamsTeamIdUsersRouteRouteWithChildren
  '/_authenticated/teams/$teamId/': typeof AuthenticatedTeamsTeamIdIndexRoute
  '/_authenticated/teams/$teamId/users/$userId': typeof AuthenticatedTeamsTeamIdUsersUserIdRouteRouteWithChildren
  '/_authenticated/teams/$teamId/policies/': typeof AuthenticatedTeamsTeamIdPoliciesIndexRoute
  '/_authenticated/teams/$teamId/roles/': typeof AuthenticatedTeamsTeamIdRolesIndexRoute
  '/_authenticated/teams/$teamId/service-accounts/': typeof AuthenticatedTeamsTeamIdServiceAccountsIndexRoute
  '/_authenticated/teams/$teamId/users/': typeof AuthenticatedTeamsTeamIdUsersIndexRoute
  '/_authenticated/teams/$teamId/policies/$policyId/': typeof AuthenticatedTeamsTeamIdPoliciesPolicyIdIndexRoute
  '/_authenticated/teams/$teamId/service-accounts/$serviceAccountId/': typeof AuthenticatedTeamsTeamIdServiceAccountsServiceAccountIdIndexRoute
  '/_authenticated/teams/$teamId/users/$userId/': typeof AuthenticatedTeamsTeamIdUsersUserIdIndexRoute
  '/_authenticated/teams/$teamId/users/$userId/roles/': typeof AuthenticatedTeamsTeamIdUsersUserIdRolesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/teams/$teamId'
    | '/teams/$teamId/policies'
    | '/teams/$teamId/roles'
    | '/teams/$teamId/service-accounts'
    | '/teams/$teamId/users'
    | '/teams/$teamId/'
    | '/teams/$teamId/users/$userId'
    | '/teams/$teamId/policies/'
    | '/teams/$teamId/roles/'
    | '/teams/$teamId/service-accounts/'
    | '/teams/$teamId/users/'
    | '/teams/$teamId/policies/$policyId'
    | '/teams/$teamId/service-accounts/$serviceAccountId'
    | '/teams/$teamId/users/$userId/'
    | '/teams/$teamId/users/$userId/roles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/teams/$teamId'
    | '/teams/$teamId/policies'
    | '/teams/$teamId/roles'
    | '/teams/$teamId/service-accounts'
    | '/teams/$teamId/users'
    | '/teams/$teamId/policies/$policyId'
    | '/teams/$teamId/service-accounts/$serviceAccountId'
    | '/teams/$teamId/users/$userId'
    | '/teams/$teamId/users/$userId/roles'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/teams/$teamId'
    | '/_authenticated/teams/$teamId/policies'
    | '/_authenticated/teams/$teamId/roles'
    | '/_authenticated/teams/$teamId/service-accounts'
    | '/_authenticated/teams/$teamId/users'
    | '/_authenticated/teams/$teamId/'
    | '/_authenticated/teams/$teamId/users/$userId'
    | '/_authenticated/teams/$teamId/policies/'
    | '/_authenticated/teams/$teamId/roles/'
    | '/_authenticated/teams/$teamId/service-accounts/'
    | '/_authenticated/teams/$teamId/users/'
    | '/_authenticated/teams/$teamId/policies/$policyId/'
    | '/_authenticated/teams/$teamId/service-accounts/$serviceAccountId/'
    | '/_authenticated/teams/$teamId/users/$userId/'
    | '/_authenticated/teams/$teamId/users/$userId/roles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/teams/$teamId': {
      id: '/_authenticated/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof AuthenticatedTeamsTeamIdRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teams/$teamId/': {
      id: '/_authenticated/teams/$teamId/'
      path: '/'
      fullPath: '/teams/$teamId/'
      preLoaderRoute: typeof AuthenticatedTeamsTeamIdIndexRouteImport
      parentRoute: typeof AuthenticatedTeamsTeamIdRouteRoute
    }
    '/_authenticated/teams/$teamId/users': {
      id: '/_authenticated/teams/$teamId/users'
      path: '/users'
      fullPath: '/teams/$teamId/users'
      preLoaderRoute: typeof AuthenticatedTeamsTeamIdUsersRouteRouteImport
      parentRoute: typeof AuthenticatedTeamsTeamIdRouteRoute
    }
    '/_authenticated/teams/$teamId/service-accounts': {
      id: '/_authenticated/teams/$teamId/service-accounts'
      path: '/service-accounts'
      fullPath: '/teams/$teamId/service-accounts'
      preLoaderRoute: typeof AuthenticatedTeamsTeamIdServiceAccountsRouteRouteImport
      parentRoute: typeof AuthenticatedTeamsTeamIdRouteRoute
    }
    '/_authenticated/teams/$teamId/roles': {
      id: '/_authenticated/teams/$teamId/roles'
      path: '/roles'
      fullPath: '/teams/$teamId/roles'
      preLoaderRoute: typeof AuthenticatedTeamsTeamIdRolesRouteRouteImport
      parentRoute: typeof AuthenticatedTeamsTeamIdRouteRoute
    }
    '/_authenticated/teams/$teamId/policies': {
      id: '/_authenticated/teams/$teamId/policies'
      path: '/policies'
      fullPath: '/teams/$teamId/policies'
      preLoaderRoute: typeof AuthenticatedTeamsTeamIdPoliciesRouteRouteImport
      parentRoute: typeof AuthenticatedTeamsTeamIdRouteRoute
    }
    '/_authenticated/teams/$teamId/users/': {
      id: '/_authenticated/teams/$teamId/users/'
      path: '/'
      fullPath: '/teams/$teamId/users/'
      preLoaderRoute: typeof AuthenticatedTeamsTeamIdUsersIndexRouteImport
      parentRoute: typeof AuthenticatedTeamsTeamIdUsersRouteRoute
    }
    '/_authenticated/teams/$teamId/service-accounts/': {
      id: '/_authenticated/teams/$teamId/service-accounts/'
      path: '/'
      fullPath: '/teams/$teamId/service-accounts/'
      preLoaderRoute: typeof AuthenticatedTeamsTeamIdServiceAccountsIndexRouteImport
      parentRoute: typeof AuthenticatedTeamsTeamIdServiceAccountsRouteRoute
    }
    '/_authenticated/teams/$teamId/roles/': {
      id: '/_authenticated/teams/$teamId/roles/'
      path: '/'
      fullPath: '/teams/$teamId/roles/'
      preLoaderRoute: typeof AuthenticatedTeamsTeamIdRolesIndexRouteImport
      parentRoute: typeof AuthenticatedTeamsTeamIdRolesRouteRoute
    }
    '/_authenticated/teams/$teamId/policies/': {
      id: '/_authenticated/teams/$teamId/policies/'
      path: '/'
      fullPath: '/teams/$teamId/policies/'
      preLoaderRoute: typeof AuthenticatedTeamsTeamIdPoliciesIndexRouteImport
      parentRoute: typeof AuthenticatedTeamsTeamIdPoliciesRouteRoute
    }
    '/_authenticated/teams/$teamId/users/$userId': {
      id: '/_authenticated/teams/$teamId/users/$userId'
      path: '/$userId'
      fullPath: '/teams/$teamId/users/$userId'
      preLoaderRoute: typeof AuthenticatedTeamsTeamIdUsersUserIdRouteRouteImport
      parentRoute: typeof AuthenticatedTeamsTeamIdUsersRouteRoute
    }
    '/_authenticated/teams/$teamId/users/$userId/': {
      id: '/_authenticated/teams/$teamId/users/$userId/'
      path: '/'
      fullPath: '/teams/$teamId/users/$userId/'
      preLoaderRoute: typeof AuthenticatedTeamsTeamIdUsersUserIdIndexRouteImport
      parentRoute: typeof AuthenticatedTeamsTeamIdUsersUserIdRouteRoute
    }
    '/_authenticated/teams/$teamId/service-accounts/$serviceAccountId/': {
      id: '/_authenticated/teams/$teamId/service-accounts/$serviceAccountId/'
      path: '/$serviceAccountId'
      fullPath: '/teams/$teamId/service-accounts/$serviceAccountId'
      preLoaderRoute: typeof AuthenticatedTeamsTeamIdServiceAccountsServiceAccountIdIndexRouteImport
      parentRoute: typeof AuthenticatedTeamsTeamIdServiceAccountsRouteRoute
    }
    '/_authenticated/teams/$teamId/policies/$policyId/': {
      id: '/_authenticated/teams/$teamId/policies/$policyId/'
      path: '/$policyId'
      fullPath: '/teams/$teamId/policies/$policyId'
      preLoaderRoute: typeof AuthenticatedTeamsTeamIdPoliciesPolicyIdIndexRouteImport
      parentRoute: typeof AuthenticatedTeamsTeamIdPoliciesRouteRoute
    }
    '/_authenticated/teams/$teamId/users/$userId/roles/': {
      id: '/_authenticated/teams/$teamId/users/$userId/roles/'
      path: '/roles'
      fullPath: '/teams/$teamId/users/$userId/roles'
      preLoaderRoute: typeof AuthenticatedTeamsTeamIdUsersUserIdRolesIndexRouteImport
      parentRoute: typeof AuthenticatedTeamsTeamIdUsersUserIdRouteRoute
    }
  }
}

interface AuthenticatedTeamsTeamIdPoliciesRouteRouteChildren {
  AuthenticatedTeamsTeamIdPoliciesIndexRoute: typeof AuthenticatedTeamsTeamIdPoliciesIndexRoute
  AuthenticatedTeamsTeamIdPoliciesPolicyIdIndexRoute: typeof AuthenticatedTeamsTeamIdPoliciesPolicyIdIndexRoute
}

const AuthenticatedTeamsTeamIdPoliciesRouteRouteChildren: AuthenticatedTeamsTeamIdPoliciesRouteRouteChildren =
  {
    AuthenticatedTeamsTeamIdPoliciesIndexRoute:
      AuthenticatedTeamsTeamIdPoliciesIndexRoute,
    AuthenticatedTeamsTeamIdPoliciesPolicyIdIndexRoute:
      AuthenticatedTeamsTeamIdPoliciesPolicyIdIndexRoute,
  }

const AuthenticatedTeamsTeamIdPoliciesRouteRouteWithChildren =
  AuthenticatedTeamsTeamIdPoliciesRouteRoute._addFileChildren(
    AuthenticatedTeamsTeamIdPoliciesRouteRouteChildren,
  )

interface AuthenticatedTeamsTeamIdRolesRouteRouteChildren {
  AuthenticatedTeamsTeamIdRolesIndexRoute: typeof AuthenticatedTeamsTeamIdRolesIndexRoute
}

const AuthenticatedTeamsTeamIdRolesRouteRouteChildren: AuthenticatedTeamsTeamIdRolesRouteRouteChildren =
  {
    AuthenticatedTeamsTeamIdRolesIndexRoute:
      AuthenticatedTeamsTeamIdRolesIndexRoute,
  }

const AuthenticatedTeamsTeamIdRolesRouteRouteWithChildren =
  AuthenticatedTeamsTeamIdRolesRouteRoute._addFileChildren(
    AuthenticatedTeamsTeamIdRolesRouteRouteChildren,
  )

interface AuthenticatedTeamsTeamIdServiceAccountsRouteRouteChildren {
  AuthenticatedTeamsTeamIdServiceAccountsIndexRoute: typeof AuthenticatedTeamsTeamIdServiceAccountsIndexRoute
  AuthenticatedTeamsTeamIdServiceAccountsServiceAccountIdIndexRoute: typeof AuthenticatedTeamsTeamIdServiceAccountsServiceAccountIdIndexRoute
}

const AuthenticatedTeamsTeamIdServiceAccountsRouteRouteChildren: AuthenticatedTeamsTeamIdServiceAccountsRouteRouteChildren =
  {
    AuthenticatedTeamsTeamIdServiceAccountsIndexRoute:
      AuthenticatedTeamsTeamIdServiceAccountsIndexRoute,
    AuthenticatedTeamsTeamIdServiceAccountsServiceAccountIdIndexRoute:
      AuthenticatedTeamsTeamIdServiceAccountsServiceAccountIdIndexRoute,
  }

const AuthenticatedTeamsTeamIdServiceAccountsRouteRouteWithChildren =
  AuthenticatedTeamsTeamIdServiceAccountsRouteRoute._addFileChildren(
    AuthenticatedTeamsTeamIdServiceAccountsRouteRouteChildren,
  )

interface AuthenticatedTeamsTeamIdUsersUserIdRouteRouteChildren {
  AuthenticatedTeamsTeamIdUsersUserIdIndexRoute: typeof AuthenticatedTeamsTeamIdUsersUserIdIndexRoute
  AuthenticatedTeamsTeamIdUsersUserIdRolesIndexRoute: typeof AuthenticatedTeamsTeamIdUsersUserIdRolesIndexRoute
}

const AuthenticatedTeamsTeamIdUsersUserIdRouteRouteChildren: AuthenticatedTeamsTeamIdUsersUserIdRouteRouteChildren =
  {
    AuthenticatedTeamsTeamIdUsersUserIdIndexRoute:
      AuthenticatedTeamsTeamIdUsersUserIdIndexRoute,
    AuthenticatedTeamsTeamIdUsersUserIdRolesIndexRoute:
      AuthenticatedTeamsTeamIdUsersUserIdRolesIndexRoute,
  }

const AuthenticatedTeamsTeamIdUsersUserIdRouteRouteWithChildren =
  AuthenticatedTeamsTeamIdUsersUserIdRouteRoute._addFileChildren(
    AuthenticatedTeamsTeamIdUsersUserIdRouteRouteChildren,
  )

interface AuthenticatedTeamsTeamIdUsersRouteRouteChildren {
  AuthenticatedTeamsTeamIdUsersUserIdRouteRoute: typeof AuthenticatedTeamsTeamIdUsersUserIdRouteRouteWithChildren
  AuthenticatedTeamsTeamIdUsersIndexRoute: typeof AuthenticatedTeamsTeamIdUsersIndexRoute
}

const AuthenticatedTeamsTeamIdUsersRouteRouteChildren: AuthenticatedTeamsTeamIdUsersRouteRouteChildren =
  {
    AuthenticatedTeamsTeamIdUsersUserIdRouteRoute:
      AuthenticatedTeamsTeamIdUsersUserIdRouteRouteWithChildren,
    AuthenticatedTeamsTeamIdUsersIndexRoute:
      AuthenticatedTeamsTeamIdUsersIndexRoute,
  }

const AuthenticatedTeamsTeamIdUsersRouteRouteWithChildren =
  AuthenticatedTeamsTeamIdUsersRouteRoute._addFileChildren(
    AuthenticatedTeamsTeamIdUsersRouteRouteChildren,
  )

interface AuthenticatedTeamsTeamIdRouteRouteChildren {
  AuthenticatedTeamsTeamIdPoliciesRouteRoute: typeof AuthenticatedTeamsTeamIdPoliciesRouteRouteWithChildren
  AuthenticatedTeamsTeamIdRolesRouteRoute: typeof AuthenticatedTeamsTeamIdRolesRouteRouteWithChildren
  AuthenticatedTeamsTeamIdServiceAccountsRouteRoute: typeof AuthenticatedTeamsTeamIdServiceAccountsRouteRouteWithChildren
  AuthenticatedTeamsTeamIdUsersRouteRoute: typeof AuthenticatedTeamsTeamIdUsersRouteRouteWithChildren
  AuthenticatedTeamsTeamIdIndexRoute: typeof AuthenticatedTeamsTeamIdIndexRoute
}

const AuthenticatedTeamsTeamIdRouteRouteChildren: AuthenticatedTeamsTeamIdRouteRouteChildren =
  {
    AuthenticatedTeamsTeamIdPoliciesRouteRoute:
      AuthenticatedTeamsTeamIdPoliciesRouteRouteWithChildren,
    AuthenticatedTeamsTeamIdRolesRouteRoute:
      AuthenticatedTeamsTeamIdRolesRouteRouteWithChildren,
    AuthenticatedTeamsTeamIdServiceAccountsRouteRoute:
      AuthenticatedTeamsTeamIdServiceAccountsRouteRouteWithChildren,
    AuthenticatedTeamsTeamIdUsersRouteRoute:
      AuthenticatedTeamsTeamIdUsersRouteRouteWithChildren,
    AuthenticatedTeamsTeamIdIndexRoute: AuthenticatedTeamsTeamIdIndexRoute,
  }

const AuthenticatedTeamsTeamIdRouteRouteWithChildren =
  AuthenticatedTeamsTeamIdRouteRoute._addFileChildren(
    AuthenticatedTeamsTeamIdRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedTeamsTeamIdRouteRoute: typeof AuthenticatedTeamsTeamIdRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedTeamsTeamIdRouteRoute:
    AuthenticatedTeamsTeamIdRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
