/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamsTeamIdUsersIndexRouteImport } from './routes/teams/$teamId/users/index'
import { Route as TeamsTeamIdUsersUserIdRouteImport } from './routes/teams/$teamId/users/$userId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamIdUsersIndexRoute = TeamsTeamIdUsersIndexRouteImport.update({
  id: '/teams/$teamId/users/',
  path: '/teams/$teamId/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamIdUsersUserIdRoute = TeamsTeamIdUsersUserIdRouteImport.update({
  id: '/teams/$teamId/users/$userId',
  path: '/teams/$teamId/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/teams/$teamId/users/$userId': typeof TeamsTeamIdUsersUserIdRoute
  '/teams/$teamId/users': typeof TeamsTeamIdUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/teams/$teamId/users/$userId': typeof TeamsTeamIdUsersUserIdRoute
  '/teams/$teamId/users': typeof TeamsTeamIdUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/teams/$teamId/users/$userId': typeof TeamsTeamIdUsersUserIdRoute
  '/teams/$teamId/users/': typeof TeamsTeamIdUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/teams/$teamId/users/$userId' | '/teams/$teamId/users'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/teams/$teamId/users/$userId' | '/teams/$teamId/users'
  id:
    | '__root__'
    | '/'
    | '/teams/$teamId/users/$userId'
    | '/teams/$teamId/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TeamsTeamIdUsersUserIdRoute: typeof TeamsTeamIdUsersUserIdRoute
  TeamsTeamIdUsersIndexRoute: typeof TeamsTeamIdUsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId/users/': {
      id: '/teams/$teamId/users/'
      path: '/teams/$teamId/users'
      fullPath: '/teams/$teamId/users'
      preLoaderRoute: typeof TeamsTeamIdUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId/users/$userId': {
      id: '/teams/$teamId/users/$userId'
      path: '/teams/$teamId/users/$userId'
      fullPath: '/teams/$teamId/users/$userId'
      preLoaderRoute: typeof TeamsTeamIdUsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TeamsTeamIdUsersUserIdRoute: TeamsTeamIdUsersUserIdRoute,
  TeamsTeamIdUsersIndexRoute: TeamsTeamIdUsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
