/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamsTeamIdRouteRouteImport } from './routes/teams/$teamId/route'
import { Route as TeamsTeamIdIndexRouteImport } from './routes/teams/$teamId/index'
import { Route as TeamsTeamIdUsersRouteRouteImport } from './routes/teams/$teamId/users/route'
import { Route as TeamsTeamIdServiceAccountsRouteRouteImport } from './routes/teams/$teamId/service-accounts/route'
import { Route as TeamsTeamIdUsersIndexRouteImport } from './routes/teams/$teamId/users/index'
import { Route as TeamsTeamIdServiceAccountsIndexRouteImport } from './routes/teams/$teamId/service-accounts/index'
import { Route as TeamsTeamIdUsersUserIdRouteRouteImport } from './routes/teams/$teamId/users/$userId/route'
import { Route as TeamsTeamIdUsersUserIdIndexRouteImport } from './routes/teams/$teamId/users/$userId/index'
import { Route as TeamsTeamIdUsersUserIdPoliciesIndexRouteImport } from './routes/teams/$teamId/users/$userId/policies/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamIdRouteRoute = TeamsTeamIdRouteRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamIdIndexRoute = TeamsTeamIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeamsTeamIdRouteRoute,
} as any)
const TeamsTeamIdUsersRouteRoute = TeamsTeamIdUsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => TeamsTeamIdRouteRoute,
} as any)
const TeamsTeamIdServiceAccountsRouteRoute =
  TeamsTeamIdServiceAccountsRouteRouteImport.update({
    id: '/service-accounts',
    path: '/service-accounts',
    getParentRoute: () => TeamsTeamIdRouteRoute,
  } as any)
const TeamsTeamIdUsersIndexRoute = TeamsTeamIdUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeamsTeamIdUsersRouteRoute,
} as any)
const TeamsTeamIdServiceAccountsIndexRoute =
  TeamsTeamIdServiceAccountsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TeamsTeamIdServiceAccountsRouteRoute,
  } as any)
const TeamsTeamIdUsersUserIdRouteRoute =
  TeamsTeamIdUsersUserIdRouteRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => TeamsTeamIdUsersRouteRoute,
  } as any)
const TeamsTeamIdUsersUserIdIndexRoute =
  TeamsTeamIdUsersUserIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TeamsTeamIdUsersUserIdRouteRoute,
  } as any)
const TeamsTeamIdUsersUserIdPoliciesIndexRoute =
  TeamsTeamIdUsersUserIdPoliciesIndexRouteImport.update({
    id: '/policies/',
    path: '/policies/',
    getParentRoute: () => TeamsTeamIdUsersUserIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/teams/$teamId': typeof TeamsTeamIdRouteRouteWithChildren
  '/teams/$teamId/service-accounts': typeof TeamsTeamIdServiceAccountsRouteRouteWithChildren
  '/teams/$teamId/users': typeof TeamsTeamIdUsersRouteRouteWithChildren
  '/teams/$teamId/': typeof TeamsTeamIdIndexRoute
  '/teams/$teamId/users/$userId': typeof TeamsTeamIdUsersUserIdRouteRouteWithChildren
  '/teams/$teamId/service-accounts/': typeof TeamsTeamIdServiceAccountsIndexRoute
  '/teams/$teamId/users/': typeof TeamsTeamIdUsersIndexRoute
  '/teams/$teamId/users/$userId/': typeof TeamsTeamIdUsersUserIdIndexRoute
  '/teams/$teamId/users/$userId/policies': typeof TeamsTeamIdUsersUserIdPoliciesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/teams/$teamId': typeof TeamsTeamIdIndexRoute
  '/teams/$teamId/service-accounts': typeof TeamsTeamIdServiceAccountsIndexRoute
  '/teams/$teamId/users': typeof TeamsTeamIdUsersIndexRoute
  '/teams/$teamId/users/$userId': typeof TeamsTeamIdUsersUserIdIndexRoute
  '/teams/$teamId/users/$userId/policies': typeof TeamsTeamIdUsersUserIdPoliciesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/teams/$teamId': typeof TeamsTeamIdRouteRouteWithChildren
  '/teams/$teamId/service-accounts': typeof TeamsTeamIdServiceAccountsRouteRouteWithChildren
  '/teams/$teamId/users': typeof TeamsTeamIdUsersRouteRouteWithChildren
  '/teams/$teamId/': typeof TeamsTeamIdIndexRoute
  '/teams/$teamId/users/$userId': typeof TeamsTeamIdUsersUserIdRouteRouteWithChildren
  '/teams/$teamId/service-accounts/': typeof TeamsTeamIdServiceAccountsIndexRoute
  '/teams/$teamId/users/': typeof TeamsTeamIdUsersIndexRoute
  '/teams/$teamId/users/$userId/': typeof TeamsTeamIdUsersUserIdIndexRoute
  '/teams/$teamId/users/$userId/policies/': typeof TeamsTeamIdUsersUserIdPoliciesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/teams/$teamId'
    | '/teams/$teamId/service-accounts'
    | '/teams/$teamId/users'
    | '/teams/$teamId/'
    | '/teams/$teamId/users/$userId'
    | '/teams/$teamId/service-accounts/'
    | '/teams/$teamId/users/'
    | '/teams/$teamId/users/$userId/'
    | '/teams/$teamId/users/$userId/policies'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/teams/$teamId'
    | '/teams/$teamId/service-accounts'
    | '/teams/$teamId/users'
    | '/teams/$teamId/users/$userId'
    | '/teams/$teamId/users/$userId/policies'
  id:
    | '__root__'
    | '/'
    | '/teams/$teamId'
    | '/teams/$teamId/service-accounts'
    | '/teams/$teamId/users'
    | '/teams/$teamId/'
    | '/teams/$teamId/users/$userId'
    | '/teams/$teamId/service-accounts/'
    | '/teams/$teamId/users/'
    | '/teams/$teamId/users/$userId/'
    | '/teams/$teamId/users/$userId/policies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TeamsTeamIdRouteRoute: typeof TeamsTeamIdRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId': {
      id: '/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof TeamsTeamIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId/': {
      id: '/teams/$teamId/'
      path: '/'
      fullPath: '/teams/$teamId/'
      preLoaderRoute: typeof TeamsTeamIdIndexRouteImport
      parentRoute: typeof TeamsTeamIdRouteRoute
    }
    '/teams/$teamId/users': {
      id: '/teams/$teamId/users'
      path: '/users'
      fullPath: '/teams/$teamId/users'
      preLoaderRoute: typeof TeamsTeamIdUsersRouteRouteImport
      parentRoute: typeof TeamsTeamIdRouteRoute
    }
    '/teams/$teamId/service-accounts': {
      id: '/teams/$teamId/service-accounts'
      path: '/service-accounts'
      fullPath: '/teams/$teamId/service-accounts'
      preLoaderRoute: typeof TeamsTeamIdServiceAccountsRouteRouteImport
      parentRoute: typeof TeamsTeamIdRouteRoute
    }
    '/teams/$teamId/users/': {
      id: '/teams/$teamId/users/'
      path: '/'
      fullPath: '/teams/$teamId/users/'
      preLoaderRoute: typeof TeamsTeamIdUsersIndexRouteImport
      parentRoute: typeof TeamsTeamIdUsersRouteRoute
    }
    '/teams/$teamId/service-accounts/': {
      id: '/teams/$teamId/service-accounts/'
      path: '/'
      fullPath: '/teams/$teamId/service-accounts/'
      preLoaderRoute: typeof TeamsTeamIdServiceAccountsIndexRouteImport
      parentRoute: typeof TeamsTeamIdServiceAccountsRouteRoute
    }
    '/teams/$teamId/users/$userId': {
      id: '/teams/$teamId/users/$userId'
      path: '/$userId'
      fullPath: '/teams/$teamId/users/$userId'
      preLoaderRoute: typeof TeamsTeamIdUsersUserIdRouteRouteImport
      parentRoute: typeof TeamsTeamIdUsersRouteRoute
    }
    '/teams/$teamId/users/$userId/': {
      id: '/teams/$teamId/users/$userId/'
      path: '/'
      fullPath: '/teams/$teamId/users/$userId/'
      preLoaderRoute: typeof TeamsTeamIdUsersUserIdIndexRouteImport
      parentRoute: typeof TeamsTeamIdUsersUserIdRouteRoute
    }
    '/teams/$teamId/users/$userId/policies/': {
      id: '/teams/$teamId/users/$userId/policies/'
      path: '/policies'
      fullPath: '/teams/$teamId/users/$userId/policies'
      preLoaderRoute: typeof TeamsTeamIdUsersUserIdPoliciesIndexRouteImport
      parentRoute: typeof TeamsTeamIdUsersUserIdRouteRoute
    }
  }
}

interface TeamsTeamIdServiceAccountsRouteRouteChildren {
  TeamsTeamIdServiceAccountsIndexRoute: typeof TeamsTeamIdServiceAccountsIndexRoute
}

const TeamsTeamIdServiceAccountsRouteRouteChildren: TeamsTeamIdServiceAccountsRouteRouteChildren =
  {
    TeamsTeamIdServiceAccountsIndexRoute: TeamsTeamIdServiceAccountsIndexRoute,
  }

const TeamsTeamIdServiceAccountsRouteRouteWithChildren =
  TeamsTeamIdServiceAccountsRouteRoute._addFileChildren(
    TeamsTeamIdServiceAccountsRouteRouteChildren,
  )

interface TeamsTeamIdUsersUserIdRouteRouteChildren {
  TeamsTeamIdUsersUserIdIndexRoute: typeof TeamsTeamIdUsersUserIdIndexRoute
  TeamsTeamIdUsersUserIdPoliciesIndexRoute: typeof TeamsTeamIdUsersUserIdPoliciesIndexRoute
}

const TeamsTeamIdUsersUserIdRouteRouteChildren: TeamsTeamIdUsersUserIdRouteRouteChildren =
  {
    TeamsTeamIdUsersUserIdIndexRoute: TeamsTeamIdUsersUserIdIndexRoute,
    TeamsTeamIdUsersUserIdPoliciesIndexRoute:
      TeamsTeamIdUsersUserIdPoliciesIndexRoute,
  }

const TeamsTeamIdUsersUserIdRouteRouteWithChildren =
  TeamsTeamIdUsersUserIdRouteRoute._addFileChildren(
    TeamsTeamIdUsersUserIdRouteRouteChildren,
  )

interface TeamsTeamIdUsersRouteRouteChildren {
  TeamsTeamIdUsersUserIdRouteRoute: typeof TeamsTeamIdUsersUserIdRouteRouteWithChildren
  TeamsTeamIdUsersIndexRoute: typeof TeamsTeamIdUsersIndexRoute
}

const TeamsTeamIdUsersRouteRouteChildren: TeamsTeamIdUsersRouteRouteChildren = {
  TeamsTeamIdUsersUserIdRouteRoute:
    TeamsTeamIdUsersUserIdRouteRouteWithChildren,
  TeamsTeamIdUsersIndexRoute: TeamsTeamIdUsersIndexRoute,
}

const TeamsTeamIdUsersRouteRouteWithChildren =
  TeamsTeamIdUsersRouteRoute._addFileChildren(
    TeamsTeamIdUsersRouteRouteChildren,
  )

interface TeamsTeamIdRouteRouteChildren {
  TeamsTeamIdServiceAccountsRouteRoute: typeof TeamsTeamIdServiceAccountsRouteRouteWithChildren
  TeamsTeamIdUsersRouteRoute: typeof TeamsTeamIdUsersRouteRouteWithChildren
  TeamsTeamIdIndexRoute: typeof TeamsTeamIdIndexRoute
}

const TeamsTeamIdRouteRouteChildren: TeamsTeamIdRouteRouteChildren = {
  TeamsTeamIdServiceAccountsRouteRoute:
    TeamsTeamIdServiceAccountsRouteRouteWithChildren,
  TeamsTeamIdUsersRouteRoute: TeamsTeamIdUsersRouteRouteWithChildren,
  TeamsTeamIdIndexRoute: TeamsTeamIdIndexRoute,
}

const TeamsTeamIdRouteRouteWithChildren =
  TeamsTeamIdRouteRoute._addFileChildren(TeamsTeamIdRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TeamsTeamIdRouteRoute: TeamsTeamIdRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
